import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import {Sidebar} from "@/app/components/sidebar/Sidebar";
import {Header} from "@/app/components/header/Header";
import { Providers } from "@/app/providers";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aura Bot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
    <body className="min-h-full flex ">
    <Providers>
      <Sidebar/>
      <div className="flex-col flex-1 h-full">
        <Header/>
        {children}
      </div>
      <Toaster richColors closeButton position="top-right" />
    </Providers>
    </body>
    </html>
  );
}
